### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by NabajitBhadury** [NabajitBhadury/Weather-Detector#1]
Make a small documentation of the entire project

**Comment by abhipriyachowdhury** [comment]
https://github.com/abhipriyachowdhury/Weather-Detector.git

plz check my readme.md file in my fork repository

**Comment by NabajitBhadury** [comment]
@abhipriyachowdhury please send a pr to my repository and your readme file has some plagiarism I expect you should update your readme.md contribution rather searching form online sources and send a healthy pr in my repository

Tip: I have explained everything in the contributing.md file already

**Comment by NabajitBhadury** [comment]
I can see your contribution but you haven't send a pull request so I can't
merge this to my project. And I have figured out that you have not updated
the contribution.md link in the contribution tag I expect that you should
change that
