### ISSUE TITLE
Fix the error 

### ISSUE THREAD

**Issue by abhipriyachowdhury** [NabajitBhadury/Weather-Detector#3]
Fix the unexpected error when I put the input as "los angeles" for detect weather of los angeles

![Screenshot 2024-01-04 012104](https://github.com/NabajitBhadury/Weather-Detector/assets/139592613/f695eef8-73a6-46a1-8c47-62adc9a5b5ae)

**Comment by NabajitBhadury** [comment]
Thanks @abhipriyachowdhury for pointing out this error hope you will fix this issue
